name: Deploy EKS Cluster

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
         role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_ID }}:role/${{ secrets.ROLE_NAME }}
         aws-region: ${{ secrets.REGION }}

    - name: Check if Stack Exists
      id: check_stack
      run: |
        STACK_NAME="MyEKSCluster"
        if aws cloudformation describe-stacks --stack-name $STACK_NAME > /dev/null 2>&1; then
          echo "exists=true" >> $GITHUB_ENV
        else
          echo "exists=false" >> $GITHUB_ENV
        fi

    - name: Keep the Stack if Exists
      if: env.exists == 'true'
      run: |
        STACK_NAME="MyEKSCluster"
        echo "Keep the stack $STACK_NAME... and do nothing"
 
    - name: Deploy EKS using CloudFormation
      if: env.exists == 'false'
      run: |
        aws cloudformation deploy \
          --template-file cloudfformation/EKS_setup.yaml \
          --stack-name MyEKSCluster \
          --capabilities CAPABILITY_NAMED_IAM

    - name: Wait for EKS Cluster to be Active
      run: |
        CLUSTER_STATUS=$(aws eks describe-cluster --name MyEKSCluster --query "cluster.status" --output text)
        while [ "$CLUSTER_STATUS" != "ACTIVE" ]; do
          echo "Waiting for EKS Cluster to become ACTIVE..."
          sleep 30
          CLUSTER_STATUS=$(aws eks describe-cluster --name MyEKSCluster --query "cluster.status" --output text)
        done
        echo "EKS Cluster is ACTIVE."

    - name: Update EKS Cluster Endpoint Access
      run: |
        aws eks update-cluster-config \
          --region ${{ secrets.AWS_REGION }} \
          --name MyEKSCluster \
          --resources-vpc-config endpointPublicAccess=false,endpointPrivateAccess=true
