name: Deploy EKS Cluster

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Check if Stack Exists
      id: check_stack
      run: |
        STACK_NAME="MyEKSCluster"
        aws cloudformation describe-stacks --stack-name $STACK_NAME || echo "Stack does not exist" > stack_status.txt

    - name: Delete Stack if Exists
      if: steps.check_stack.outputs.stack_status != 'Stack does not exist'
      run: |
        STACK_NAME="MyEKSCluster"
        echo "Deleting stack $STACK_NAME..."
        aws cloudformation delete-stack --stack-name $STACK_NAME
        echo "Stack $STACK_NAME deletion initiated."

    - name: Wait for Stack Deletion to Complete
      if: steps.check_stack.outputs.stack_status != 'Stack does not exist'
      run: |
        STACK_NAME="MyEKSCluster"
        echo "Waiting for stack $STACK_NAME deletion to complete..."
        aws cloudformation wait stack-delete-complete --stack-name $STACK_NAME
        echo "Stack $STACK_NAME deletion completed."  

    - name: Deploy EKS using CloudFormation
      run: |
        aws cloudformation deploy \
          --template-file cloudfformation/EKS_setup.yaml \
          --stack-name MyEKSCluster \
          --capabilities CAPABILITY_NAMED_IAM
