name: Deploy EKS Cluster

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Check if Stack Exists
      id: check_stack
      run: |
        STACK_NAME="MyEKSCluster"
        aws cloudformation describe-stacks --stack-name $STACK_NAME || echo "Stack does not exist" > stack_status.txt

    - name: Delete Stack if Exists
      if: steps.check_stack.outputs.stack_status != 'Stack does not exist'
      run: |
        echo "Keep the stack $STACK_NAME... and do nothing"
 
    - name: Deploy EKS using CloudFormation
      if: steps.check_stack.outputs.stack_status == 'Stack does not exist'
      run: |
        aws cloudformation deploy \
          --template-file cloudfformation/EKS_setup.yaml \
          --stack-name MyEKSCluster \
          --capabilities CAPABILITY_NAMED_IAM

    - name: Wait for EKS Cluster to be Active
      run: |
        CLUSTER_STATUS=$(aws eks describe-cluster --name MyEKSCluster --query "cluster.status" --output text)
        while [ "$CLUSTER_STATUS" != "ACTIVE" ]; do
          echo "Waiting for EKS Cluster to become ACTIVE..."
          sleep 30
          CLUSTER_STATUS=$(aws eks describe-cluster --name MyEKSCluster --query "cluster.status" --output text)
        done
        echo "EKS Cluster is ACTIVE."

    - name: Update EKS Cluster Endpoint Access
      run: |
        aws eks update-cluster-config \
          --region ${{ secrets.AWS_REGION }} \
          --name MyEKSCluster \
          --resources-vpc-config endpointPublicAccess=false,endpointPrivateAccess=true
